import { StyleSheet } from 'react-native';

import { REVIEW_COLORS, rs } from './review-theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: REVIEW_COLORS.surface,
  },
  screen: {
    flex: 1,
    backgroundColor: REVIEW_COLORS.surface,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs(8),
    paddingHorizontal: rs(20),
    paddingTop: rs(10),
    paddingBottom: rs(12),
  },
  backButton: {
    height: rs(36),
    width: rs(36),
    borderRadius: rs(18),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  headerTitle: {
    fontSize: rs(24),
    fontWeight: '700',
    color: REVIEW_COLORS.textPrimary,
  },
  headerDivider: {
    height: 1,
    backgroundColor: REVIEW_COLORS.border,
  },
  sortSection: {
    paddingHorizontal: rs(20),
    paddingTop: rs(10),
    paddingBottom: rs(10),
    gap: rs(10),
  },
  sortLabel: {
    fontSize: rs(13),
    fontWeight: '700',
    color: REVIEW_COLORS.textSecondary,
  },
  sortRow: {
    flexDirection: 'row',
    gap: rs(12),
  },
  sortChip: {
    paddingHorizontal: rs(16),
    paddingVertical: rs(8),
    borderRadius: 999,
    backgroundColor: REVIEW_COLORS.surfaceMuted,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  sortChipActive: {
    backgroundColor: REVIEW_COLORS.accent,
    borderColor: REVIEW_COLORS.accent,
  },
  sortChipText: {
    fontSize: rs(13),
    fontWeight: '700',
    color: REVIEW_COLORS.chipText,
  },
  sortChipTextActive: {
    color: REVIEW_COLORS.chipTextActive,
  },
  scrollContent: {
    paddingHorizontal: rs(20),
    paddingBottom: rs(120),
    gap: rs(14),
  },
  reviewCard: {
    backgroundColor: REVIEW_COLORS.surface,
    borderRadius: rs(16),
    padding: rs(14),
    borderWidth: 1,
    borderColor: REVIEW_COLORS.border,
    position: 'relative',
  },
  reviewPressable: {
    flex: 1,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs(12),
  },
  avatar: {
    width: rs(32),
    height: rs(32),
    borderRadius: rs(16),
  },
  reviewMeta: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: rs(8),
    paddingRight: rs(36),
  },
  reviewActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs(8),
  },
  deleteButton: {
    position: 'absolute',
    top: rs(10),
    right: rs(10),
    zIndex: 2,
    width: rs(28),
    height: rs(28),
    borderRadius: rs(14),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: REVIEW_COLORS.surfaceMuted,
  },
  destinationTitle: {
    fontSize: rs(15),
    fontWeight: '700',
    color: REVIEW_COLORS.textPrimary,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: rs(6),
  },
  reviewTime: {
    fontSize: rs(12),
    fontWeight: '600',
    color: REVIEW_COLORS.textSecondary,
  },
  reviewBody: {
    marginTop: rs(8),
    fontSize: rs(13),
    lineHeight: rs(18),
    color: REVIEW_COLORS.textSecondary,
  },
  reviewTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: rs(8),
    marginTop: rs(8),
  },
  reviewTagChip: {
    paddingHorizontal: rs(10),
    paddingVertical: rs(4),
    borderRadius: 999,
    backgroundColor: REVIEW_COLORS.chip,
  },
  reviewTagText: {
    fontSize: rs(11),
    fontWeight: '700',
    color: REVIEW_COLORS.chipText,
  },
  statusText: {
    fontSize: rs(12),
    fontWeight: '600',
    color: REVIEW_COLORS.textSecondary,
    lineHeight: rs(16),
  },
  errorText: {
    fontSize: rs(12),
    fontWeight: '600',
    color: REVIEW_COLORS.error,
    lineHeight: rs(16),
  },
  viewMoreButton: {
    marginTop: rs(8),
    marginBottom: rs(16),
    alignSelf: 'center',
    paddingHorizontal: rs(32),
    paddingVertical: rs(10),
    borderRadius: 999,
    borderWidth: 1,
    borderColor: REVIEW_COLORS.border,
    backgroundColor: REVIEW_COLORS.surface,
  },
  viewMoreText: {
    fontSize: rs(13),
    fontWeight: '700',
    color: REVIEW_COLORS.textPrimary,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: rs(24),
  },
  modalCard: {
    width: '100%',
    borderRadius: rs(18),
    backgroundColor: REVIEW_COLORS.surface,
    padding: rs(18),
    borderWidth: 1,
    borderColor: REVIEW_COLORS.border,
  },
  modalTitle: {
    fontSize: rs(16),
    fontWeight: '700',
    color: REVIEW_COLORS.textPrimary,
  },
  modalBody: {
    marginTop: rs(6),
    fontSize: rs(13),
    color: REVIEW_COLORS.textSecondary,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: rs(10),
    marginTop: rs(16),
  },
  modalCancelButton: {
    paddingHorizontal: rs(14),
    paddingVertical: rs(10),
    borderRadius: rs(10),
    backgroundColor: REVIEW_COLORS.surfaceMuted,
  },
  modalCancelText: {
    fontSize: rs(12),
    fontWeight: '700',
    color: REVIEW_COLORS.textPrimary,
  },
  modalDeleteButton: {
    paddingHorizontal: rs(14),
    paddingVertical: rs(10),
    borderRadius: rs(10),
    backgroundColor: REVIEW_COLORS.error,
  },
  modalDeleteText: {
    fontSize: rs(12),
    fontWeight: '700',
    color: REVIEW_COLORS.buttonText,
  },
});
