import { StyleSheet } from 'react-native';

import { REVIEW_COLORS, REVIEW_FONTS, rs } from './review-theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: REVIEW_COLORS.background,
  },
  screen: {
    flex: 1,
    backgroundColor: REVIEW_COLORS.background,
  },
  backgroundOrb: {
    position: 'absolute',
    top: -140,
    right: -110,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: REVIEW_COLORS.accentSoft,
    opacity: 0.75,
  },
  backgroundOrbTwo: {
    position: 'absolute',
    top: 240,
    left: -120,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: REVIEW_COLORS.accentWarm,
    opacity: 0.55,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: rs(20),
    paddingTop: rs(10),
    paddingBottom: rs(6),
    gap: rs(10),
  },
  backButton: {
    height: rs(36),
    width: rs(36),
    borderRadius: rs(12),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: REVIEW_COLORS.surface,
    borderWidth: 1,
    borderColor: REVIEW_COLORS.border,
  },
  headerTitle: {
    flex: 1,
    fontSize: rs(22),
    fontWeight: '700',
    color: REVIEW_COLORS.textPrimary,
    fontFamily: REVIEW_FONTS.heading,
  },
  postButton: {
    paddingHorizontal: rs(16),
    paddingVertical: rs(8),
    borderRadius: 999,
    backgroundColor: REVIEW_COLORS.accent,
  },
  postButtonDisabled: {
    opacity: 0.6,
  },
  postButtonText: {
    fontSize: rs(12),
    fontWeight: '700',
    color: REVIEW_COLORS.buttonText,
    fontFamily: REVIEW_FONTS.body,
  },
  scrollContent: {
    paddingHorizontal: rs(20),
    paddingBottom: rs(32),
    gap: rs(18),
  },
  summaryWrapper: {
    marginTop: rs(8),
  },
  section: {
    gap: rs(10),
  },
  sectionLabel: {
    fontSize: rs(14),
    fontWeight: '700',
    color: REVIEW_COLORS.textPrimary,
    fontFamily: REVIEW_FONTS.body,
  },
  reviewInput: {
    minHeight: rs(120),
    borderRadius: rs(16),
    borderWidth: 1,
    borderColor: REVIEW_COLORS.border,
    backgroundColor: REVIEW_COLORS.surface,
    padding: rs(14),
    fontSize: rs(13),
    lineHeight: rs(18),
    color: REVIEW_COLORS.textPrimary,
    fontFamily: REVIEW_FONTS.body,
  },
  charCount: {
    fontSize: rs(11),
    fontWeight: '600',
    color: REVIEW_COLORS.textSecondary,
    fontFamily: REVIEW_FONTS.body,
  },
  statusText: {
    fontSize: rs(12),
    fontWeight: '600',
    color: '#1F7A57',
    fontFamily: REVIEW_FONTS.body,
  },
  errorText: {
    fontSize: rs(12),
    fontWeight: '600',
    color: '#D54545',
    fontFamily: REVIEW_FONTS.body,
  },
  photoRow: {
    gap: rs(12),
  },
  addPhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: rs(8),
    paddingHorizontal: rs(12),
    paddingVertical: rs(10),
    borderRadius: rs(12),
    borderWidth: 1,
    borderColor: REVIEW_COLORS.accent,
    backgroundColor: REVIEW_COLORS.accentSoft,
    alignSelf: 'flex-start',
  },
  addPhotoText: {
    fontSize: rs(12),
    fontWeight: '700',
    color: REVIEW_COLORS.accent,
    fontFamily: REVIEW_FONTS.body,
  },
  photoThumbRow: {
    flexDirection: 'row',
    gap: rs(12),
    flexWrap: 'wrap',
  },
  photoThumb: {
    width: rs(70),
    height: rs(70),
    borderRadius: rs(12),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: REVIEW_COLORS.border,
    backgroundColor: REVIEW_COLORS.surfaceMuted,
  },
  photoImage: {
    width: '100%',
    height: '100%',
  },
  removeBadge: {
    position: 'absolute',
    top: rs(6),
    right: rs(6),
    width: rs(18),
    height: rs(18),
    borderRadius: rs(9),
    backgroundColor: REVIEW_COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: rs(8),
  },
  tagChip: {
    paddingHorizontal: rs(12),
    paddingVertical: rs(6),
    borderRadius: 999,
    backgroundColor: REVIEW_COLORS.chip,
  },
  tagChipActive: {
    backgroundColor: REVIEW_COLORS.chipActive,
  },
  tagText: {
    fontSize: rs(12),
    fontWeight: '700',
    color: REVIEW_COLORS.chipText,
    fontFamily: REVIEW_FONTS.body,
  },
  tagTextActive: {
    color: REVIEW_COLORS.chipTextActive,
  },
});
