import { StyleSheet } from 'react-native';

export const DISCOVER_THEME = {
  spacing: 8,
  borderRadius: 25,
  colors: {
    primary: '#008D9B',
    background: '#FFFFFF',
    textPrimary: '#000000',
    textSecondary: '#A19D9D',
    navIconInactive: '#62707A',
    searchBackground: '#E3E8EC',
    searchIcon: '#4E5A64',
    handle: '#CDD0D4',
    cardBorder: '#CFCFCF',
    cardShadow: '#000000',
    ratingIconBackground: '#FFF4CC',
    plusBackground: '#D7EDF0',
    navBorder: '#D9D9D9',
  },
} as const;

const { spacing, borderRadius, colors } = DISCOVER_THEME;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollArea: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: spacing * 3,
    paddingHorizontal: spacing * 3,
    paddingBottom: spacing * 16,
  },
  header: {
    color: colors.textPrimary,
    fontSize: 42,
    lineHeight: 46,
    fontWeight: '700',
    marginBottom: spacing * 2,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing * 2,
    marginBottom: spacing * 2,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.searchBackground,
    borderRadius: borderRadius,
    paddingHorizontal: spacing * 2,
    height: spacing * 5,
  },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 16,
    marginRight: spacing,
    paddingVertical: 0,
  },
  filterButton: {
    height: spacing * 6,
    width: spacing * 6,
    borderRadius: spacing * 3,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  handleBar: {
    width: 170,
    height: 6,
    borderRadius: 99,
    backgroundColor: colors.handle,
    marginBottom: spacing * 3,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 30,
    fontWeight: '700',
    marginBottom: spacing * 2,
  },
  cardList: {
    gap: spacing * 2,
  },
  noResultsText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '500',
  },
  card: {
    borderRadius: borderRadius,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    shadowColor: colors.cardShadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  imageWrapper: {
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: 190,
  },
  ratingPill: {
    position: 'absolute',
    left: spacing * 2,
    bottom: spacing,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 20,
    paddingHorizontal: spacing,
    paddingVertical: spacing * 0.75,
    gap: spacing * 0.5,
  },
  ratingIconWrap: {
    height: 20,
    width: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.ratingIconBackground,
  },
  ratingText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  cardBody: {
    paddingHorizontal: spacing * 3,
    paddingTop: spacing * 2,
    paddingBottom: spacing * 1.5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  cardTextGroup: {
    gap: spacing * 0.5,
    flexShrink: 1,
    paddingRight: spacing,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '600',
  },
  cardRegion: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '500',
  },
  cardVisited: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '500',
  },
  cardActionGroup: {
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 70,
    gap: spacing * 1.5,
    paddingTop: spacing * 0.5,
  },
  plusButton: {
    height: 36,
    width: 36,
    borderRadius: 18,
    backgroundColor: colors.plusBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButton: {
    minHeight: 32,
    minWidth: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
    zIndex: 19,
  },
  filterPanel: {
    position: 'absolute',
    top: spacing * 14,
    right: spacing * 3,
    width: 238,
    backgroundColor: colors.background,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E7E7E7',
    padding: spacing * 2,
    shadowColor: colors.cardShadow,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 10,
    zIndex: 20,
  },
  filterPanelTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: spacing * 1.5,
  },
  filterChipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing,
  },
  filterChip: {
    borderWidth: 1,
    borderColor: '#D6D6D6',
    borderRadius: 999,
    paddingHorizontal: spacing * 1.5,
    paddingVertical: spacing * 0.75,
    backgroundColor: colors.background,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: {
    color: '#4D5965',
    fontSize: 13,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: colors.background,
  },
  filterActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing,
    marginTop: spacing * 2,
  },
  clearFilterButton: {
    borderWidth: 1,
    borderColor: '#D1D1D1',
    borderRadius: 999,
    paddingHorizontal: spacing * 1.5,
    paddingVertical: spacing,
  },
  clearFilterText: {
    color: '#5B6570',
    fontSize: 13,
    fontWeight: '600',
  },
  applyFilterButton: {
    borderRadius: 999,
    paddingHorizontal: spacing * 1.75,
    paddingVertical: spacing,
    backgroundColor: colors.primary,
  },
  applyFilterText: {
    color: colors.background,
    fontSize: 13,
    fontWeight: '700',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.navBorder,
    paddingHorizontal: spacing * 2,
    paddingTop: spacing,
    zIndex: 21,
    elevation: 12,
  },
  bottomItem: {
    alignItems: 'center',
    gap: spacing * 0.25,
    minWidth: 56,
  },
  bottomLabel: {
    color: colors.navIconInactive,
    fontSize: 12,
    fontWeight: '600',
  },
  bottomLabelActive: {
    color: colors.primary,
  },
});