import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E7E7E7",
  },
  headerTitle: {
    fontSize: 34,
    fontWeight: "800",
    color: "#111827",
  },
  headerIconButton: {
    padding: 4,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  profileSection: {
    alignItems: "center",
    paddingTop: 26,
    paddingHorizontal: 24,
  },
  avatarButton: {
    width: 100,
    height: 100,
    marginBottom: 12,
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 46,
  },
  avatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E2E8F0',
  },
  avatarInitials: {
    fontSize: 28,
    fontWeight: '700',
    color: '#334155',
  },
  avatarEditBadge: {
    position: 'absolute',
    right: 2,
    bottom: 6,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#008D9B',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    fontSize: 28,
    fontWeight: "700",
    color: "#111827",
  },
  username: {
    fontSize: 15,
    color: "#64748B",
    marginTop: 4,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 22,
    marginBottom: 18,
  },
  statBlock: {
    alignItems: "center",
    minWidth: 80,
  },
  statValue: {
    fontSize: 30,
    fontWeight: "700",
    color: "#111827",
  },
  statLabel: {
    marginTop: 2,
    fontSize: 14,
    color: "#64748B",
  },
  statDivider: {
    width: 1,
    height: 42,
    backgroundColor: "#D9D9D9",
    marginHorizontal: 18,
  },
  editButton: {
    backgroundColor: "#E9EEF4",
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 999,
  },
  editButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#222222",
  },
  cardsSection: {
    marginTop: 28,
    paddingHorizontal: 18,
    gap: 14,
  },
  actionCard: {
    minHeight: 92,
    borderWidth: 1.5,
    borderColor: "#D7EEF0",
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 18,
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#008D9B",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  actionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  actionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  actionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111827",
  },
  actionSubtitle: {
    marginTop: 4,
    fontSize: 14,
    color: "#64748B",
  },
  settingsSection: {
    marginTop: 26,
    paddingHorizontal: 22,
  },
  logoutMessage: {
    marginTop: 10,
    fontSize: 12,
    color: '#D54545',
  },
  settingsHeading: {
    fontSize: 22,
    fontWeight: "700",
    color: "#6B6B6B",
    marginBottom: 12,
  },
  settingsRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  settingsLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  settingsText: {
    fontSize: 18,
    color: "#222222",
    fontWeight: "500",
  },
});
