import React, { useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { COLORS, Header, TabBar, OptionCard, Checkmark, RadioCircle, VotedLabel, VoteProgress, VoterAvatars } from './_components';
import { BudgetOption, VotingTab } from './_types';

export default function BudgetVotingScreen({ tripName='Voting', budgetOptions, onTabChange, onBack, onVote, onCreateBudgetOption, totalBudgetMin=0, totalBudgetMax=0, votingFinished, canManageOptions, onDeleteOption }:{tripName?:string;budgetOptions:BudgetOption[];onTabChange?:(tab:VotingTab)=>void;onBack?:()=>void;onVote?:(id:string)=>void;onCreateBudgetOption?:(min:number,max:number)=>void;totalBudgetMin?:number;totalBudgetMax?:number;votingFinished?:boolean;canManageOptions?:boolean;onDeleteOption?:(id:string)=>void;}){
  const [minBudget,setMinBudget]=useState(''); const [maxBudget,setMaxBudget]=useState(''); const [err,setErr]=useState<string|null>(null); const [pendingDelete,setPendingDelete]=useState<string|null>(null);
  const add=()=>{const min=Number(minBudget),max=Number(maxBudget); if(!minBudget||!maxBudget){setErr('Min and max budget are required.');return;} if(!Number.isFinite(min)||!Number.isFinite(max)||min<=0||max<=0){setErr('Budgets must be positive numbers.');return;} if(min>max){setErr('Min budget must be less than or equal to max budget.');return;} setErr(null); onCreateBudgetOption?.(min,max); setMinBudget(''); setMaxBudget('');};
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.keyboardAvoider} behavior={Platform.OS === 'ios' ? 'padding' : Platform.OS === 'android' ? 'height' : undefined}><Header title={tripName} onBack={onBack}/><TabBar tabs={['Dates','Budget']} activeTab='Budget' onTabPress={(t)=>onTabChange?.(t as VotingTab)} />
    {votingFinished ? <View style={styles.closedPill}><Text style={styles.closedText}>Voting is closed</Text></View> : null}
    <ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps='handled'>
      {budgetOptions.map((o)=><View key={o.id} style={{position:'relative'}}><OptionCard selected={o.selected} onPress={()=>!votingFinished && onVote?.(o.id)}><Text style={styles.label}>{`€${o.min} - €${o.max}`}</Text><VotedLabel votedCount={o.votedCount} totalMembers={o.totalMembers}/><VoteProgress votedCount={o.votedCount} totalMembers={o.totalMembers}/><VoterAvatars voters={o.voters} totalMembers={o.totalMembers}/><View style={styles.ind}>{o.selected?<Checkmark/>:<RadioCircle/>}</View></OptionCard>{canManageOptions && !votingFinished ? <Pressable hitSlop={12} onPress={(e)=>{e.stopPropagation?.();setPendingDelete(o.id);}} style={styles.x}><Text style={styles.xText}>✕</Text></Pressable>:null}</View>)}
      <Text style={styles.total}>{`Total budget range: €${totalBudgetMin} - €${totalBudgetMax}`}</Text>
      <Text style={styles.label2}>Min budget (€)</Text><TextInput keyboardType='numeric' value={minBudget} onChangeText={setMinBudget} editable={!votingFinished} style={styles.input}/>
      <Text style={styles.label2}>Max budget (€)</Text><TextInput keyboardType='numeric' value={maxBudget} onChangeText={setMaxBudget} editable={!votingFinished} style={styles.input}/>
      {err ? <Text style={styles.err}>{err}</Text> : null}
      <Pressable disabled={Boolean(votingFinished)} onPress={add} style={[styles.btn,votingFinished&&{opacity:.5}]}><Text style={styles.btnText}>Add Budget Option</Text></Pressable>
    </ScrollView>
    <Modal transparent visible={Boolean(pendingDelete)} onRequestClose={()=>setPendingDelete(null)}><View style={styles.modalBg}><View style={styles.modal}><Text style={styles.modalTitle}>Delete budget option?</Text><Text style={styles.modalBody}>Are you sure you want to delete this budget option?</Text><View style={styles.row}><Pressable onPress={()=>setPendingDelete(null)}><Text>Cancel</Text></Pressable><Pressable onPress={()=>{ if(pendingDelete) onDeleteOption?.(pendingDelete); setPendingDelete(null); }}><Text style={{color:'#BE123C',fontWeight:'700'}}>Delete</Text></Pressable></View></View></View></Modal></KeyboardAvoidingView>
  </SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},keyboardAvoider:{flex:1},scroll:{flex:1},content:{padding:16,paddingBottom:220},label:{fontWeight:'600',fontSize:16},ind:{position:'absolute',right:8,top:8},label2:{marginTop:10,fontWeight:'600'},input:{borderWidth:1,borderColor:'#CBD5E1',borderRadius:10,paddingHorizontal:12,paddingVertical:10,marginTop:6},btn:{marginTop:14,backgroundColor:COLORS.buttonBg,borderRadius:10,padding:14,alignItems:'center'},btnText:{color:COLORS.buttonText,fontWeight:'700'},err:{marginTop:8,color:'#BE123C'},total:{marginTop:8,color:'#0F172A',fontWeight:'700'},closedPill:{alignSelf:'flex-start',marginHorizontal:16,marginTop:8,backgroundColor:'#FCE7F3',paddingHorizontal:10,paddingVertical:6,borderRadius:999},closedText:{color:'#BE123C',fontWeight:'700',fontSize:12},x:{position:'absolute',top:10,right:10,zIndex:50,elevation:50,width:32,height:32,borderRadius:16,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},xText:{color:'#BE123C',fontWeight:'800'},modalBg:{flex:1,backgroundColor:'rgba(0,0,0,0.35)',alignItems:'center',justifyContent:'center',padding:24},modal:{backgroundColor:'#fff',borderRadius:16,padding:18,width:'100%',maxWidth:340},modalTitle:{fontWeight:'800',fontSize:18},modalBody:{marginTop:8,color:'#64748B'},row:{marginTop:16,flexDirection:'row',justifyContent:'flex-end',gap:16}})
