import React, { useState } from 'react';
import { Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { COLORS, Header, TabBar, OptionCard, Checkmark, RadioCircle, VotedLabel, VoteProgress, VoterAvatars } from './_components';
import { DateOption, VotingTab } from './_types';

const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const DAYS=['Su','Mo','Tu','We','Th','Fr','Sa'];

function Calendar({disabled,onSelect}:{disabled?:boolean;onSelect:(start:Date,end:Date)=>void}){
 const t=new Date(); const [y,setY]=useState(t.getFullYear()); const [m,setM]=useState(t.getMonth()); const [start,setStart]=useState<Date|null>(null); const [end,setEnd]=useState<Date|null>(null);
 const first=new Date(y,m,1).getDay(); const dim=new Date(y,m+1,0).getDate(); const cells=[...Array(first).fill(null),...Array.from({length:dim},(_,i)=>i+1)]; while(cells.length%7) cells.push(null);
 const pick=(d:number)=>{ if(disabled) return; const cur=new Date(y,m,d); if(!start||end){setStart(cur);setEnd(null); return;} const s=cur<start?cur:start; const e=cur<start?start:cur; setStart(s); setEnd(e); onSelect(s,e); };
 const inRange=(d:number)=>start&&end&&new Date(y,m,d)>start&&new Date(y,m,d)<end;
 const isStart=(d:number)=>start&&new Date(y,m,d).toDateString()===start.toDateString(); const isEnd=(d:number)=>end&&new Date(y,m,d).toDateString()===end.toDateString();
 return <View style={styles.calWrap}><View style={styles.calNav}><Pressable onPress={()=>setM((v)=>v===0?(setY(y-1),11):v-1)}><Text style={styles.nav}>‹</Text></Pressable><Text style={styles.calTitle}>{MONTHS[m]} {y}</Text><Pressable onPress={()=>setM((v)=>v===11?(setY(y+1),0):v+1)}><Text style={styles.nav}>›</Text></Pressable></View><View style={styles.week}>{DAYS.map((d)=><Text key={d} style={styles.weekTxt}>{d}</Text>)}</View><View style={styles.grid}>{cells.map((d,i)=><Pressable key={i} style={styles.cell} onPress={()=>d&&pick(d)}>{d?<View style={[styles.dot,inRange(d)&&styles.range,(isStart(d)||isEnd(d))&&styles.sel]}><Text style={[styles.day,(isStart(d)||isEnd(d))&&{color:'#fff'}]}>{d}</Text></View>:null}</Pressable>)}</View></View>
}

export default function DateVotingScreen({ tripName='Voting', dateOptions, onTabChange, onBack, onVote, onCreateDateOption, votingFinished, canManageOptions, onDeleteOption }:{tripName?:string;dateOptions:DateOption[];onTabChange?:(tab:VotingTab)=>void;onBack?:()=>void;onVote?:(id:string)=>void;onCreateDateOption?:(start:Date,end:Date)=>void;votingFinished?:boolean;canManageOptions?:boolean;onDeleteOption?:(id:string)=>void;}){
  const [pendingDelete, setPendingDelete] = useState<string | null>(null);
  const [selectedLabel,setSelectedLabel]=useState('');
  return <SafeAreaView style={styles.safe}><Header title={tripName} onBack={onBack} />
    <TabBar tabs={['Dates','Budget']} activeTab='Dates' onTabPress={(t)=>onTabChange?.(t as VotingTab)} />
    {votingFinished ? <View style={styles.closedPill}><Text style={styles.closedText}>Voting is closed</Text></View> : null}
    <ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      {dateOptions.map((o)=><View key={o.id} style={{position:'relative'}}><OptionCard selected={o.selected} onPress={()=>!votingFinished && onVote?.(o.id)}><Text style={styles.label}>{o.label}</Text><VotedLabel votedCount={o.votedCount} totalMembers={o.totalMembers}/><VoteProgress votedCount={o.votedCount} totalMembers={o.totalMembers}/><VoterAvatars voters={o.voters} totalMembers={o.totalMembers}/><View style={styles.ind}>{o.selected?<Checkmark/>:<RadioCircle/>}</View></OptionCard>{canManageOptions && !votingFinished ? <Pressable hitSlop={12} onPress={(e)=>{e.stopPropagation?.();setPendingDelete(o.id);}} style={styles.x}><Text style={styles.xText}>✕</Text></Pressable>:null}</View>)}
      <Text style={styles.subTitle}>Select another date range</Text>
      <Calendar disabled={Boolean(votingFinished)} onSelect={(s,e)=>{ setSelectedLabel(`${MONTHS[s.getMonth()]} ${s.getDate()}–${e.getDate()}, ${e.getFullYear()}`); onCreateDateOption?.(s,e); }} />
      {selectedLabel ? <Text style={styles.selected}>{selectedLabel}</Text> : null}
    </ScrollView>
    <Modal transparent visible={Boolean(pendingDelete)} onRequestClose={()=>setPendingDelete(null)}><View style={styles.modalBg}><View style={styles.modal}><Text style={styles.modalTitle}>Delete date option?</Text><Text style={styles.modalBody}>Are you sure you want to delete this date option?</Text><View style={styles.row}><Pressable style={styles.cancelBtn} onPress={()=>setPendingDelete(null)}><Text>Cancel</Text></Pressable><Pressable style={styles.deleteBtn} onPress={()=>{ if(pendingDelete) onDeleteOption?.(pendingDelete); setPendingDelete(null); }}><Text style={{color:'#fff',fontWeight:'700'}}>Delete</Text></Pressable></View></View></View></Modal>
  </SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},scroll:{flex:1},content:{padding:16,paddingBottom:220},label:{fontWeight:'600',fontSize:16},ind:{position:'absolute',right:8,top:8},subTitle:{marginTop:12,fontWeight:'700',color:COLORS.textPrimary},selected:{marginTop:8,color:COLORS.primaryDark,fontWeight:'600'},closedPill:{alignSelf:'flex-start',marginHorizontal:16,marginTop:8,backgroundColor:'#FCE7F3',paddingHorizontal:10,paddingVertical:6,borderRadius:999},closedText:{color:'#BE123C',fontWeight:'700',fontSize:12},x:{position:'absolute',top:10,right:10,zIndex:50,elevation:50,width:32,height:32,borderRadius:16,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},xText:{color:'#BE123C',fontWeight:'800'},calWrap:{marginTop:8,borderWidth:1,borderColor:COLORS.border,borderRadius:12,padding:10},calNav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},calTitle:{fontWeight:'700',color:COLORS.textPrimary},nav:{fontSize:22,color:COLORS.primary},week:{flexDirection:'row',marginTop:8},weekTxt:{flex:1,textAlign:'center',fontSize:12,color:COLORS.textMuted},grid:{flexDirection:'row',flexWrap:'wrap'},cell:{width:'14.28%',aspectRatio:1,alignItems:'center',justifyContent:'center'},dot:{width:30,height:30,borderRadius:15,alignItems:'center',justifyContent:'center'},day:{color:COLORS.textPrimary},sel:{backgroundColor:COLORS.primary},range:{backgroundColor:'#CCFBF1'},modalBg:{flex:1,backgroundColor:'rgba(0,0,0,0.35)',alignItems:'center',justifyContent:'center',padding:24},modal:{backgroundColor:'#fff',borderRadius:16,padding:18,width:'100%',maxWidth:340},modalTitle:{fontWeight:'800',fontSize:18},modalBody:{marginTop:8,color:'#64748B'},row:{marginTop:16,flexDirection:'row',justifyContent:'flex-end',gap:12},cancelBtn:{paddingHorizontal:14,paddingVertical:10,borderRadius:10,backgroundColor:'#E2E8F0'},deleteBtn:{paddingHorizontal:14,paddingVertical:10,borderRadius:10,backgroundColor:'#BE123C'}})
