import React, { useState } from 'react';
import { Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { COLORS, Header, TabBar, OptionCard, Checkmark, RadioCircle, VotedLabel, VoteProgress, VoterAvatars } from './_components';
import { DateOption, VotingTab } from './_types';

export default function DateVotingScreen({ tripName='Voting', dateOptions, onTabChange, onBack, onVote, onCreateDateOption, votingFinished, canManageOptions, onDeleteOption }:{tripName?:string;dateOptions:DateOption[];onTabChange?:(tab:VotingTab)=>void;onBack?:()=>void;onVote?:(id:string)=>void;onCreateDateOption?:(start:Date,end:Date)=>void;votingFinished?:boolean;canManageOptions?:boolean;onDeleteOption?:(id:string)=>void;}){
  const [pendingDelete, setPendingDelete] = useState<string | null>(null);
  const now = new Date();
  return <SafeAreaView style={styles.safe}><Header title={tripName} onBack={onBack} />
    <TabBar tabs={['Dates','Budget']} activeTab='Dates' onTabPress={(t)=>onTabChange?.(t as VotingTab)} />
    {votingFinished ? <View style={styles.closedPill}><Text style={styles.closedText}>Voting is closed</Text></View> : null}
    <ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      {dateOptions.map((o)=><View key={o.id} style={{position:'relative'}}><OptionCard selected={o.selected} onPress={()=>!votingFinished && onVote?.(o.id)}><Text style={styles.label}>{o.label}</Text><VotedLabel votedCount={o.votedCount} totalMembers={o.totalMembers}/><VoteProgress votedCount={o.votedCount} totalMembers={o.totalMembers}/><VoterAvatars voters={o.voters} totalMembers={o.totalMembers}/><View style={styles.ind}>{o.selected?<Checkmark/>:<RadioCircle/>}</View></OptionCard>{canManageOptions && !votingFinished ? <Pressable hitSlop={12} onPress={(e)=>{e.stopPropagation?.();setPendingDelete(o.id);}} style={styles.x}><Text style={styles.xText}>✕</Text></Pressable>:null}</View>)}
      <TouchableOpacity disabled={Boolean(votingFinished)} style={styles.btn} onPress={()=>onCreateDateOption?.(now,new Date(now.getTime()+86400000))}><Text style={styles.btnText}>Add Date Option</Text></TouchableOpacity>
    </ScrollView>
    <Modal transparent visible={Boolean(pendingDelete)} onRequestClose={()=>setPendingDelete(null)}><View style={styles.modalBg}><View style={styles.modal}><Text style={styles.modalTitle}>Delete date option?</Text><Text style={styles.modalBody}>Are you sure you want to delete this date option?</Text><View style={styles.row}><Pressable onPress={()=>setPendingDelete(null)}><Text>Cancel</Text></Pressable><Pressable onPress={()=>{ if(pendingDelete) onDeleteOption?.(pendingDelete); setPendingDelete(null); }}><Text style={{color:'#BE123C',fontWeight:'700'}}>Delete</Text></Pressable></View></View></View></Modal>
  </SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},scroll:{flex:1},content:{padding:16,paddingBottom:220},label:{fontWeight:'600',fontSize:16},ind:{position:'absolute',right:8,top:8},btn:{marginTop:14,backgroundColor:COLORS.buttonBg,borderRadius:10,padding:14,alignItems:'center'},btnText:{color:COLORS.buttonText,fontWeight:'700'},closedPill:{alignSelf:'flex-start',marginHorizontal:16,marginTop:8,backgroundColor:'#FCE7F3',paddingHorizontal:10,paddingVertical:6,borderRadius:999},closedText:{color:'#BE123C',fontWeight:'700',fontSize:12},x:{position:'absolute',top:10,right:10,zIndex:50,elevation:50,width:32,height:32,borderRadius:16,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},xText:{color:'#BE123C',fontWeight:'800'},modalBg:{flex:1,backgroundColor:'rgba(0,0,0,0.35)',alignItems:'center',justifyContent:'center',padding:24},modal:{backgroundColor:'#fff',borderRadius:16,padding:18,width:'100%',maxWidth:340},modalTitle:{fontWeight:'800',fontSize:18},modalBody:{marginTop:8,color:'#64748B'},row:{marginTop:16,flexDirection:'row',justifyContent:'flex-end',gap:16}})
